// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v5.27.2
// source: fleetcontroller.proto

package fleetpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	FleetStatusService_ListInstances_FullMethodName = "/fleetcontroller.v1.FleetStatusService/ListInstances"
	FleetStatusService_GetInstance_FullMethodName   = "/fleetcontroller.v1.FleetStatusService/GetInstance"
	FleetStatusService_SelectHost_FullMethodName    = "/fleetcontroller.v1.FleetStatusService/SelectHost"
)

// FleetStatusServiceClient is the client API for FleetStatusService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FleetStatusServiceClient interface {
	ListInstances(ctx context.Context, in *ListInstancesRequest, opts ...grpc.CallOption) (*ListInstancesResponse, error)
	GetInstance(ctx context.Context, in *GetInstanceRequest, opts ...grpc.CallOption) (*GetInstanceResponse, error)
	SelectHost(ctx context.Context, in *SelectHostRequest, opts ...grpc.CallOption) (*SelectHostResponse, error)
}

type fleetStatusServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFleetStatusServiceClient(cc grpc.ClientConnInterface) FleetStatusServiceClient {
	return &fleetStatusServiceClient{cc}
}

func (c *fleetStatusServiceClient) ListInstances(ctx context.Context, in *ListInstancesRequest, opts ...grpc.CallOption) (*ListInstancesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListInstancesResponse)
	err := c.cc.Invoke(ctx, FleetStatusService_ListInstances_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetStatusServiceClient) GetInstance(ctx context.Context, in *GetInstanceRequest, opts ...grpc.CallOption) (*GetInstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInstanceResponse)
	err := c.cc.Invoke(ctx, FleetStatusService_GetInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetStatusServiceClient) SelectHost(ctx context.Context, in *SelectHostRequest, opts ...grpc.CallOption) (*SelectHostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SelectHostResponse)
	err := c.cc.Invoke(ctx, FleetStatusService_SelectHost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FleetStatusServiceServer is the server API for FleetStatusService service.
// All implementations must embed UnimplementedFleetStatusServiceServer
// for forward compatibility
type FleetStatusServiceServer interface {
	ListInstances(context.Context, *ListInstancesRequest) (*ListInstancesResponse, error)
	GetInstance(context.Context, *GetInstanceRequest) (*GetInstanceResponse, error)
	SelectHost(context.Context, *SelectHostRequest) (*SelectHostResponse, error)
	mustEmbedUnimplementedFleetStatusServiceServer()
}

// UnimplementedFleetStatusServiceServer must be embedded to have forward compatible implementations.
type UnimplementedFleetStatusServiceServer struct {
}

func (UnimplementedFleetStatusServiceServer) ListInstances(context.Context, *ListInstancesRequest) (*ListInstancesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListInstances not implemented")
}
func (UnimplementedFleetStatusServiceServer) GetInstance(context.Context, *GetInstanceRequest) (*GetInstanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInstance not implemented")
}
func (UnimplementedFleetStatusServiceServer) SelectHost(context.Context, *SelectHostRequest) (*SelectHostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SelectHost not implemented")
}
func (UnimplementedFleetStatusServiceServer) mustEmbedUnimplementedFleetStatusServiceServer() {}

// UnsafeFleetStatusServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FleetStatusServiceServer will
// result in compilation errors.
type UnsafeFleetStatusServiceServer interface {
	mustEmbedUnimplementedFleetStatusServiceServer()
}

func RegisterFleetStatusServiceServer(s grpc.ServiceRegistrar, srv FleetStatusServiceServer) {
	s.RegisterService(&FleetStatusService_ServiceDesc, srv)
}

func _FleetStatusService_ListInstances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInstancesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetStatusServiceServer).ListInstances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetStatusService_ListInstances_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetStatusServiceServer).ListInstances(ctx, req.(*ListInstancesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetStatusService_GetInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetStatusServiceServer).GetInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetStatusService_GetInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetStatusServiceServer).GetInstance(ctx, req.(*GetInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetStatusService_SelectHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SelectHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetStatusServiceServer).SelectHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetStatusService_SelectHost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetStatusServiceServer).SelectHost(ctx, req.(*SelectHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FleetStatusService_ServiceDesc is the grpc.ServiceDesc for FleetStatusService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FleetStatusService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fleetcontroller.v1.FleetStatusService",
	HandlerType: (*FleetStatusServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListInstances",
			Handler:    _FleetStatusService_ListInstances_Handler,
		},
		{
			MethodName: "GetInstance",
			Handler:    _FleetStatusService_GetInstance_Handler,
		},
		{
			MethodName: "SelectHost",
			Handler:    _FleetStatusService_SelectHost_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fleetcontroller.proto",
}
